# Turn on validation, so we can use import:
version: ~> 1.0

import:
- land-of-apps/land-of-apps:travis/ruby-imports.yml

services:
- postgresql

addons:
  chrome: stable

before_script:
- travis_wait ./bin/setup

script:
- APPMAP=true bundle exec rspec && APPMAP=true bundle exec appraisal rspec

after_script:
- env DEBUG=true ruby ./upload-appmaps tmp/appmap/rspec