# Turn on validation, so we can use import:
version: ~> 1.0

services:
- postgresql

addons:
  chrome: stable

before_script:
- wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -o /usr/bin/google-chrome
- export CHROME_BIN=chromium-browser
- travis_wait ./bin/setup

script:
- bundle exec rspec && bundle exec appraisal rspec
