# Turn on validation, so we can use import:
version: ~> 1.0

services:
- postgresql

gemfile:
- gemfiles/rails50.gemfile
- gemfiles/rails51.gemfile
- gemfiles/rails52.gemfile
- gemfiles/rails60.gemfile

before_script:
- ./bin/setup

script:
- bundle exec rspec && bundle exec appraisal rspec
